import { Card } from "./types";

export const cards: Array<Card> = [
  { rank: '6', suit: 'diamonds', img: 'cards/1b.bmp' },
  { rank: '6', suit: 'hearts', img: 'cards/1c.bmp' },
  { rank: '6', suit: 'clubs', img: 'cards/1k.bmp' },
  { rank: '6', suit: 'spades', img: 'cards/1p.bmp' },
  { rank: '7', suit: 'diamonds', img: 'cards/2b.bmp' },
  { rank: '7', suit: 'hearts', img: 'cards/2c.bmp' },
  { rank: '7', suit: 'clubs', img: 'cards/2k.bmp' },
  { rank: '7', suit: 'spades', img: 'cards/2p.bmp' },
  { rank: '8', suit: 'diamonds', img: 'cards/3b.bmp' },
  { rank: '8', suit: 'hearts', img: 'cards/3c.bmp' },
  { rank: '8', suit: 'clubs', img: 'cards/3k.bmp' },
  { rank: '8', suit: 'spades', img: 'cards/3p.bmp' },
  { rank: '9', suit: 'diamonds', img: 'cards/4b.bmp' },
  { rank: '9', suit: 'hearts', img: 'cards/4c.bmp' },
  { rank: '9', suit: 'clubs', img: 'cards/4k.bmp' },
  { rank: '9', suit: 'spades', img: 'cards/4p.bmp' },
  { rank: '10', suit: 'diamonds', img: 'cards/5b.bmp' },
  { rank: '10', suit: 'hearts', img: 'cards/5c.bmp' },
  { rank: '10', suit: 'clubs', img: 'cards/5k.bmp' },
  { rank: '10', suit: 'spades', img: 'cards/5p.bmp' },
  { rank: 'J', suit: 'diamonds', img: 'cards/6b.bmp' },
  { rank: 'J', suit: 'hearts', img: 'cards/6c.bmp' },
  { rank: 'J', suit: 'clubs', img: 'cards/6k.bmp' },
  { rank: 'J', suit: 'spades', img: 'cards/6p.bmp' },
  { rank: 'Q', suit: 'diamonds', img: 'cards/7b.bmp' },
  { rank: 'Q', suit: 'hearts', img: 'cards/7c.bmp' },
  { rank: 'Q', suit: 'clubs', img: 'cards/7k.bmp' },
  { rank: 'Q', suit: 'spades', img: 'cards/7p.bmp' },
  { rank: 'K', suit: 'diamonds', img: 'cards/8b.bmp' },
  { rank: 'K', suit: 'hearts', img: 'cards/8c.bmp' },
  { rank: 'K', suit: 'clubs', img: 'cards/8k.bmp' },
  { rank: 'K', suit: 'spades', img: 'cards/8p.bmp' },
  { rank: 'A', suit: 'diamonds', img: 'cards/9b.bmp' },
  { rank: 'A', suit: 'hearts', img: 'cards/9c.bmp' },
  { rank: 'A', suit: 'clubs', img: 'cards/9k.bmp' },
  { rank: 'A', suit: 'spades', img: 'cards/9p.bmp' },
];
